// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql"
	"time"
)

type ConfigRevision struct {
	ID         int64
	CreatedAt  time.Time
	Source     string
	ConfigHash string
	ConfigYaml []byte
	Active     int64
}

type ConsoleAdmin struct {
	ID           int64
	PasswordHash []byte
	CreatedAt    int64
}

type ConsoleSession struct {
	TokenHash string
	CsrfToken string
	ExpiresAt int64
	CreatedAt int64
}

type HostResourceSample struct {
	RecordedAt           time.Time
	IntervalSeconds      int64
	CpuPercent           float64
	MemoryUsedBytes      int64
	MemoryAvailableBytes int64
	DiskUsedBytes        int64
	DiskAvailableBytes   int64
	DiskReadBytes        int64
	DiskWriteBytes       int64
	LoadOne              float64
	TemperatureCelsius   float64
}

type Job struct {
	ID                 string
	RunnerName         string
	RunnerSetName      string
	Result             string
	StartedAt          time.Time
	CompletedAt        sql.NullTime
	Owner              string
	Repository         string
	WorkflowRef        string
	DisplayName        string
	WorkflowRunID      int64
	EventName          string
	LabelsJson         string
	QueuedAt           sql.NullTime
	ScaleSetAssignedAt sql.NullTime
	RunnerAssignedAt   sql.NullTime
	Backend            string
}

type JobLog struct {
	Sequence   int64
	JobID      string
	RecordedAt time.Time
	Text       string
}

type JobResourceSample struct {
	ID                   int64
	JobID                string
	RecordedAt           time.Time
	Source               string
	Accuracy             string
	CpuPercent           float64
	MemoryUsedBytes      int64
	MemoryAvailableBytes int64
	DiskUsedBytes        int64
	DiskAvailableBytes   int64
	DiskReadBytes        int64
	DiskWriteBytes       int64
	NetworkReceiveBytes  int64
	NetworkSendBytes     int64
}
