// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const clearActiveConfigRevision = `-- name: ClearActiveConfigRevision :exec
UPDATE config_revisions SET active = 0
`

func (q *Queries) ClearActiveConfigRevision(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearActiveConfigRevision)
	return err
}

const countAdmin = `-- name: CountAdmin :one
SELECT COUNT(*) FROM console_admin WHERE id = 1
`

func (q *Queries) CountAdmin(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM console_admin
`

func (q *Queries) DeleteAdmin(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAdmin)
	return err
}

const deleteAllSessions = `-- name: DeleteAllSessions :exec
DELETE FROM console_sessions
`

func (q *Queries) DeleteAllSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSessions)
	return err
}

const deleteCompletedJob = `-- name: DeleteCompletedJob :exec
DELETE FROM jobs WHERE id = ? AND result != 'running'
`

func (q *Queries) DeleteCompletedJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCompletedJob, id)
	return err
}

const deleteExpiredHostSamples = `-- name: DeleteExpiredHostSamples :exec
DELETE FROM host_resource_samples
WHERE (interval_seconds = 5 AND recorded_at < ?1)
    OR recorded_at < ?2
`

type DeleteExpiredHostSamplesParams struct {
	RawCutoff     time.Time
	HistoryCutoff time.Time
}

func (q *Queries) DeleteExpiredHostSamples(ctx context.Context, arg DeleteExpiredHostSamplesParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredHostSamples, arg.RawCutoff, arg.HistoryCutoff)
	return err
}

const deleteExpiredJobLogs = `-- name: DeleteExpiredJobLogs :exec
DELETE FROM job_logs
WHERE recorded_at < ?1 OR job_id IN (
    SELECT id FROM jobs
    WHERE result != 'running' AND COALESCE(completed_at, started_at) < ?1
)
`

func (q *Queries) DeleteExpiredJobLogs(ctx context.Context, cutoff time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredJobLogs, cutoff)
	return err
}

const deleteExpiredJobResourceSamples = `-- name: DeleteExpiredJobResourceSamples :exec
DELETE FROM job_resource_samples
WHERE recorded_at < ?1 OR job_id IN (
    SELECT id FROM jobs
    WHERE result != 'running' AND COALESCE(completed_at, started_at) < ?1
)
`

func (q *Queries) DeleteExpiredJobResourceSamples(ctx context.Context, cutoff time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredJobResourceSamples, cutoff)
	return err
}

const deleteExpiredJobs = `-- name: DeleteExpiredJobs :exec
DELETE FROM jobs
WHERE result != 'running' AND COALESCE(completed_at, started_at) < ?
`

func (q *Queries) DeleteExpiredJobs(ctx context.Context, completedAt sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredJobs, completedAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM console_sessions WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteJobLogs = `-- name: DeleteJobLogs :exec
DELETE FROM job_logs WHERE job_id = ?
`

func (q *Queries) DeleteJobLogs(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, deleteJobLogs, jobID)
	return err
}

const deleteJobResourceSamples = `-- name: DeleteJobResourceSamples :exec
DELETE FROM job_resource_samples WHERE job_id = ?
`

func (q *Queries) DeleteJobResourceSamples(ctx context.Context, jobID string) error {
	_, err := q.db.ExecContext(ctx, deleteJobResourceSamples, jobID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM console_sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const getAdminPasswordHash = `-- name: GetAdminPasswordHash :one
SELECT password_hash FROM console_admin WHERE id = 1
`

func (q *Queries) GetAdminPasswordHash(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getAdminPasswordHash)
	var password_hash []byte
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getConfigRevisionYAML = `-- name: GetConfigRevisionYAML :one
SELECT config_yaml FROM config_revisions WHERE id = ?
`

func (q *Queries) GetConfigRevisionYAML(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getConfigRevisionYAML, id)
	var config_yaml []byte
	err := row.Scan(&config_yaml)
	return config_yaml, err
}

const getEarliestHostSampleTime = `-- name: GetEarliestHostSampleTime :one
SELECT recorded_at FROM host_resource_samples
ORDER BY recorded_at
LIMIT 1
`

func (q *Queries) GetEarliestHostSampleTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getEarliestHostSampleTime)
	var recorded_at time.Time
	err := row.Scan(&recorded_at)
	return recorded_at, err
}

const getJob = `-- name: GetJob :one
SELECT id, runner_name, runner_set_name, result, started_at, completed_at, owner, repository, workflow_ref, display_name, workflow_run_id, event_name, labels_json, queued_at, scale_set_assigned_at, runner_assigned_at, backend FROM jobs
WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RunnerName,
		&i.RunnerSetName,
		&i.Result,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Owner,
		&i.Repository,
		&i.WorkflowRef,
		&i.DisplayName,
		&i.WorkflowRunID,
		&i.EventName,
		&i.LabelsJson,
		&i.QueuedAt,
		&i.ScaleSetAssignedAt,
		&i.RunnerAssignedAt,
		&i.Backend,
	)
	return i, err
}

const getLastActiveConfigYAML = `-- name: GetLastActiveConfigYAML :one
SELECT config_yaml FROM config_revisions
WHERE active = 1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastActiveConfigYAML(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getLastActiveConfigYAML)
	var config_yaml []byte
	err := row.Scan(&config_yaml)
	return config_yaml, err
}

const getOldestCompletedJobSize = `-- name: GetOldestCompletedJobSize :one
SELECT jobs.id,
    CAST(4096
        + COALESCE((SELECT SUM(LENGTH(text)) FROM job_logs WHERE job_id = jobs.id), 0)
        + COALESCE((SELECT COUNT(*) * 256 FROM job_resource_samples WHERE job_id = jobs.id), 0)
    AS INTEGER) AS estimated_bytes
FROM jobs
WHERE result != 'running'
ORDER BY COALESCE(completed_at, started_at)
LIMIT 1
`

type GetOldestCompletedJobSizeRow struct {
	ID             string
	EstimatedBytes int64
}

func (q *Queries) GetOldestCompletedJobSize(ctx context.Context) (GetOldestCompletedJobSizeRow, error) {
	row := q.db.QueryRowContext(ctx, getOldestCompletedJobSize)
	var i GetOldestCompletedJobSizeRow
	err := row.Scan(&i.ID, &i.EstimatedBytes)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT csrf_token, expires_at
FROM console_sessions
WHERE token_hash = ?
`

type GetSessionRow struct {
	CsrfToken string
	ExpiresAt int64
}

func (q *Queries) GetSession(ctx context.Context, tokenHash string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, tokenHash)
	var i GetSessionRow
	err := row.Scan(&i.CsrfToken, &i.ExpiresAt)
	return i, err
}

const insertCompletedJob = `-- name: InsertCompletedJob :exec
INSERT OR IGNORE INTO jobs (id, runner_name, runner_set_name, result, started_at, completed_at)
VALUES (?, '', '', ?, ?, ?)
`

type InsertCompletedJobParams struct {
	ID          string
	Result      string
	StartedAt   time.Time
	CompletedAt sql.NullTime
}

func (q *Queries) InsertCompletedJob(ctx context.Context, arg InsertCompletedJobParams) error {
	_, err := q.db.ExecContext(ctx, insertCompletedJob,
		arg.ID,
		arg.Result,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}

const insertConfigRevision = `-- name: InsertConfigRevision :exec
INSERT INTO config_revisions (created_at, source, config_hash, config_yaml, active)
VALUES (?, ?, ?, ?, ?)
`

type InsertConfigRevisionParams struct {
	CreatedAt  time.Time
	Source     string
	ConfigHash string
	ConfigYaml []byte
	Active     int64
}

func (q *Queries) InsertConfigRevision(ctx context.Context, arg InsertConfigRevisionParams) error {
	_, err := q.db.ExecContext(ctx, insertConfigRevision,
		arg.CreatedAt,
		arg.Source,
		arg.ConfigHash,
		arg.ConfigYaml,
		arg.Active,
	)
	return err
}

const insertJobLog = `-- name: InsertJobLog :exec
INSERT INTO job_logs (job_id, recorded_at, text)
VALUES (?, ?, ?)
`

type InsertJobLogParams struct {
	JobID      string
	RecordedAt time.Time
	Text       string
}

func (q *Queries) InsertJobLog(ctx context.Context, arg InsertJobLogParams) error {
	_, err := q.db.ExecContext(ctx, insertJobLog, arg.JobID, arg.RecordedAt, arg.Text)
	return err
}

const insertJobResourceSample = `-- name: InsertJobResourceSample :exec
INSERT INTO job_resource_samples (
    job_id, recorded_at, source, accuracy, cpu_percent, memory_used_bytes,
    memory_available_bytes, disk_used_bytes, disk_available_bytes,
    disk_read_bytes, disk_write_bytes, network_receive_bytes, network_send_bytes
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertJobResourceSampleParams struct {
	JobID                string
	RecordedAt           time.Time
	Source               string
	Accuracy             string
	CpuPercent           float64
	MemoryUsedBytes      int64
	MemoryAvailableBytes int64
	DiskUsedBytes        int64
	DiskAvailableBytes   int64
	DiskReadBytes        int64
	DiskWriteBytes       int64
	NetworkReceiveBytes  int64
	NetworkSendBytes     int64
}

func (q *Queries) InsertJobResourceSample(ctx context.Context, arg InsertJobResourceSampleParams) error {
	_, err := q.db.ExecContext(ctx, insertJobResourceSample,
		arg.JobID,
		arg.RecordedAt,
		arg.Source,
		arg.Accuracy,
		arg.CpuPercent,
		arg.MemoryUsedBytes,
		arg.MemoryAvailableBytes,
		arg.DiskUsedBytes,
		arg.DiskAvailableBytes,
		arg.DiskReadBytes,
		arg.DiskWriteBytes,
		arg.NetworkReceiveBytes,
		arg.NetworkSendBytes,
	)
	return err
}

const insertRawHostSample = `-- name: InsertRawHostSample :exec
INSERT INTO host_resource_samples (
    recorded_at, interval_seconds, cpu_percent, memory_used_bytes,
    memory_available_bytes, disk_used_bytes, disk_available_bytes,
    disk_read_bytes, disk_write_bytes, load_one, temperature_celsius
) VALUES (?, 5, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertRawHostSampleParams struct {
	RecordedAt           time.Time
	CpuPercent           float64
	MemoryUsedBytes      int64
	MemoryAvailableBytes int64
	DiskUsedBytes        int64
	DiskAvailableBytes   int64
	DiskReadBytes        int64
	DiskWriteBytes       int64
	LoadOne              float64
	TemperatureCelsius   float64
}

func (q *Queries) InsertRawHostSample(ctx context.Context, arg InsertRawHostSampleParams) error {
	_, err := q.db.ExecContext(ctx, insertRawHostSample,
		arg.RecordedAt,
		arg.CpuPercent,
		arg.MemoryUsedBytes,
		arg.MemoryAvailableBytes,
		arg.DiskUsedBytes,
		arg.DiskAvailableBytes,
		arg.DiskReadBytes,
		arg.DiskWriteBytes,
		arg.LoadOne,
		arg.TemperatureCelsius,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO console_sessions (token_hash, csrf_token, expires_at, created_at)
VALUES (?, ?, ?, ?)
`

type InsertSessionParams struct {
	TokenHash string
	CsrfToken string
	ExpiresAt int64
	CreatedAt int64
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.TokenHash,
		arg.CsrfToken,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const listHostSamples = `-- name: ListHostSamples :many
SELECT recorded_at, interval_seconds, cpu_percent, memory_used_bytes,
    memory_available_bytes, disk_used_bytes, disk_available_bytes,
    disk_read_bytes, disk_write_bytes, load_one, temperature_celsius
FROM host_resource_samples
WHERE interval_seconds = ? AND recorded_at >= ? AND recorded_at <= ?
ORDER BY recorded_at
`

type ListHostSamplesParams struct {
	IntervalSeconds int64
	RecordedAt      time.Time
	RecordedAt_2    time.Time
}

func (q *Queries) ListHostSamples(ctx context.Context, arg ListHostSamplesParams) ([]HostResourceSample, error) {
	rows, err := q.db.QueryContext(ctx, listHostSamples, arg.IntervalSeconds, arg.RecordedAt, arg.RecordedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HostResourceSample
	for rows.Next() {
		var i HostResourceSample
		if err := rows.Scan(
			&i.RecordedAt,
			&i.IntervalSeconds,
			&i.CpuPercent,
			&i.MemoryUsedBytes,
			&i.MemoryAvailableBytes,
			&i.DiskUsedBytes,
			&i.DiskAvailableBytes,
			&i.DiskReadBytes,
			&i.DiskWriteBytes,
			&i.LoadOne,
			&i.TemperatureCelsius,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobLogsAfterSequence = `-- name: ListJobLogsAfterSequence :many
SELECT sequence, recorded_at, text
FROM job_logs
WHERE job_id = ? AND sequence > ?
ORDER BY sequence
LIMIT ?
`

type ListJobLogsAfterSequenceParams struct {
	JobID    string
	Sequence int64
	Limit    int64
}

type ListJobLogsAfterSequenceRow struct {
	Sequence   int64
	RecordedAt time.Time
	Text       string
}

func (q *Queries) ListJobLogsAfterSequence(ctx context.Context, arg ListJobLogsAfterSequenceParams) ([]ListJobLogsAfterSequenceRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobLogsAfterSequence, arg.JobID, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobLogsAfterSequenceRow
	for rows.Next() {
		var i ListJobLogsAfterSequenceRow
		if err := rows.Scan(&i.Sequence, &i.RecordedAt, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobResourceSamples = `-- name: ListJobResourceSamples :many
SELECT recorded_at, source, accuracy, cpu_percent, memory_used_bytes,
    memory_available_bytes, disk_used_bytes, disk_available_bytes,
    disk_read_bytes, disk_write_bytes, network_receive_bytes, network_send_bytes
FROM job_resource_samples
WHERE job_id = ?
ORDER BY recorded_at
`

type ListJobResourceSamplesRow struct {
	RecordedAt           time.Time
	Source               string
	Accuracy             string
	CpuPercent           float64
	MemoryUsedBytes      int64
	MemoryAvailableBytes int64
	DiskUsedBytes        int64
	DiskAvailableBytes   int64
	DiskReadBytes        int64
	DiskWriteBytes       int64
	NetworkReceiveBytes  int64
	NetworkSendBytes     int64
}

func (q *Queries) ListJobResourceSamples(ctx context.Context, jobID string) ([]ListJobResourceSamplesRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobResourceSamples, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobResourceSamplesRow
	for rows.Next() {
		var i ListJobResourceSamplesRow
		if err := rows.Scan(
			&i.RecordedAt,
			&i.Source,
			&i.Accuracy,
			&i.CpuPercent,
			&i.MemoryUsedBytes,
			&i.MemoryAvailableBytes,
			&i.DiskUsedBytes,
			&i.DiskAvailableBytes,
			&i.DiskReadBytes,
			&i.DiskWriteBytes,
			&i.NetworkReceiveBytes,
			&i.NetworkSendBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsNewestFirst = `-- name: ListJobsNewestFirst :many
SELECT id, runner_name, runner_set_name, result, started_at, completed_at, owner, repository, workflow_ref, display_name, workflow_run_id, event_name, labels_json, queued_at, scale_set_assigned_at, runner_assigned_at, backend FROM jobs
ORDER BY started_at DESC
LIMIT 2000
`

func (q *Queries) ListJobsNewestFirst(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsNewestFirst)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.RunnerName,
			&i.RunnerSetName,
			&i.Result,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Owner,
			&i.Repository,
			&i.WorkflowRef,
			&i.DisplayName,
			&i.WorkflowRunID,
			&i.EventName,
			&i.LabelsJson,
			&i.QueuedAt,
			&i.ScaleSetAssignedAt,
			&i.RunnerAssignedAt,
			&i.Backend,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentConfigRevisions = `-- name: ListRecentConfigRevisions :many
SELECT id, created_at, source, config_hash
FROM config_revisions
ORDER BY created_at DESC
LIMIT 10
`

type ListRecentConfigRevisionsRow struct {
	ID         int64
	CreatedAt  time.Time
	Source     string
	ConfigHash string
}

func (q *Queries) ListRecentConfigRevisions(ctx context.Context) ([]ListRecentConfigRevisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentConfigRevisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentConfigRevisionsRow
	for rows.Next() {
		var i ListRecentConfigRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Source,
			&i.ConfigHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupHostMinute = `-- name: RollupHostMinute :exec
INSERT OR REPLACE INTO host_resource_samples (
    recorded_at, interval_seconds, cpu_percent, memory_used_bytes,
    memory_available_bytes, disk_used_bytes, disk_available_bytes,
    disk_read_bytes, disk_write_bytes, load_one, temperature_celsius
)
SELECT ?1, 60, AVG(raw.cpu_percent), AVG(raw.memory_used_bytes),
    AVG(raw.memory_available_bytes), AVG(raw.disk_used_bytes), AVG(raw.disk_available_bytes),
    MAX(raw.disk_read_bytes), MAX(raw.disk_write_bytes), AVG(raw.load_one),
    AVG(raw.temperature_celsius)
FROM host_resource_samples AS raw
WHERE raw.interval_seconds = 5 AND raw.recorded_at >= ?1 AND raw.recorded_at < ?2
`

type RollupHostMinuteParams struct {
	MinuteStart time.Time
	MinuteEnd   time.Time
}

func (q *Queries) RollupHostMinute(ctx context.Context, arg RollupHostMinuteParams) error {
	_, err := q.db.ExecContext(ctx, rollupHostMinute, arg.MinuteStart, arg.MinuteEnd)
	return err
}

const trimConfigRevisions = `-- name: TrimConfigRevisions :exec
DELETE FROM config_revisions WHERE id NOT IN (
    SELECT id FROM config_revisions ORDER BY created_at DESC LIMIT 10
)
`

func (q *Queries) TrimConfigRevisions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, trimConfigRevisions)
	return err
}

const updateJobCompleted = `-- name: UpdateJobCompleted :execresult
UPDATE jobs
SET result = ?, completed_at = ?
WHERE id = ?
`

type UpdateJobCompletedParams struct {
	Result      string
	CompletedAt sql.NullTime
	ID          string
}

func (q *Queries) UpdateJobCompleted(ctx context.Context, arg UpdateJobCompletedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateJobCompleted, arg.Result, arg.CompletedAt, arg.ID)
}

const upsertAdminPassword = `-- name: UpsertAdminPassword :exec
INSERT INTO console_admin (id, password_hash, created_at)
VALUES (1, ?, ?)
ON CONFLICT(id) DO UPDATE SET password_hash = excluded.password_hash, created_at = excluded.created_at
`

type UpsertAdminPasswordParams struct {
	PasswordHash []byte
	CreatedAt    int64
}

func (q *Queries) UpsertAdminPassword(ctx context.Context, arg UpsertAdminPasswordParams) error {
	_, err := q.db.ExecContext(ctx, upsertAdminPassword, arg.PasswordHash, arg.CreatedAt)
	return err
}

const upsertStartedJob = `-- name: UpsertStartedJob :exec
INSERT INTO jobs (
    id, runner_name, runner_set_name, result, started_at, owner, repository,
    workflow_ref, display_name, workflow_run_id, event_name, labels_json,
    queued_at, scale_set_assigned_at, runner_assigned_at, backend
) VALUES (?, ?, ?, 'running', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    runner_name = excluded.runner_name,
    runner_set_name = excluded.runner_set_name,
    result = 'running',
    owner = excluded.owner,
    repository = excluded.repository,
    workflow_ref = excluded.workflow_ref,
    display_name = excluded.display_name,
    workflow_run_id = excluded.workflow_run_id,
    event_name = excluded.event_name,
    labels_json = excluded.labels_json,
    queued_at = excluded.queued_at,
    scale_set_assigned_at = excluded.scale_set_assigned_at,
    runner_assigned_at = excluded.runner_assigned_at,
    backend = excluded.backend
`

type UpsertStartedJobParams struct {
	ID                 string
	RunnerName         string
	RunnerSetName      string
	StartedAt          time.Time
	Owner              string
	Repository         string
	WorkflowRef        string
	DisplayName        string
	WorkflowRunID      int64
	EventName          string
	LabelsJson         string
	QueuedAt           sql.NullTime
	ScaleSetAssignedAt sql.NullTime
	RunnerAssignedAt   sql.NullTime
	Backend            string
}

func (q *Queries) UpsertStartedJob(ctx context.Context, arg UpsertStartedJobParams) error {
	_, err := q.db.ExecContext(ctx, upsertStartedJob,
		arg.ID,
		arg.RunnerName,
		arg.RunnerSetName,
		arg.StartedAt,
		arg.Owner,
		arg.Repository,
		arg.WorkflowRef,
		arg.DisplayName,
		arg.WorkflowRunID,
		arg.EventName,
		arg.LabelsJson,
		arg.QueuedAt,
		arg.ScaleSetAssignedAt,
		arg.RunnerAssignedAt,
		arg.Backend,
	)
	return err
}
