// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

const insertCompletedJob = `-- name: InsertCompletedJob :exec
INSERT OR IGNORE INTO jobs (id, runner_name, runner_set_name, result, started_at, completed_at)
VALUES (?, '', '', ?, ?, ?)
`

type InsertCompletedJobParams struct {
	ID          string
	Result      string
	StartedAt   time.Time
	CompletedAt sql.NullTime
}

func (q *Queries) InsertCompletedJob(ctx context.Context, arg InsertCompletedJobParams) error {
	_, err := q.db.ExecContext(ctx, insertCompletedJob,
		arg.ID,
		arg.Result,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO jobs (
    id,
    runner_name,
    runner_set_name,
    result,
    started_at,
    repository,
    workflow_name,
    workflow_run_id
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertJobParams struct {
	ID            string
	RunnerName    string
	RunnerSetName string
	Result        string
	StartedAt     time.Time
	Repository    string
	WorkflowName  string
	WorkflowRunID string
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.ExecContext(ctx, insertJob,
		arg.ID,
		arg.RunnerName,
		arg.RunnerSetName,
		arg.Result,
		arg.StartedAt,
		arg.Repository,
		arg.WorkflowName,
		arg.WorkflowRunID,
	)
	return err
}

const listRecentJobs = `-- name: ListRecentJobs :many
SELECT id,
       runner_name,
       runner_set_name,
       result,
       started_at,
       completed_at,
       repository,
       workflow_name,
       workflow_run_id
FROM jobs
ORDER BY started_at DESC
LIMIT ?
`

func (q *Queries) ListRecentJobs(ctx context.Context, limit int64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listRecentJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.RunnerName,
			&i.RunnerSetName,
			&i.Result,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Repository,
			&i.WorkflowName,
			&i.WorkflowRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobCompleted = `-- name: UpdateJobCompleted :execresult
UPDATE jobs
SET result = ?, completed_at = ?
WHERE id = ?
`

type UpdateJobCompletedParams struct {
	Result      string
	CompletedAt sql.NullTime
	ID          string
}

func (q *Queries) UpdateJobCompleted(ctx context.Context, arg UpdateJobCompletedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateJobCompleted, arg.Result, arg.CompletedAt, arg.ID)
}
