name: Integration Test

on:
  workflow_dispatch:

jobs:
  test-macos-arm64:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: mochaaP/neofetch-action@v1
      - name: neofetch
        run: neofetch

  test-linux-arm64:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - uses: mochaaP/neofetch-action@v1
      - name: neofetch
        run: neofetch

  test-linux-amd64:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: mochaaP/neofetch-action@v1
      - name: neofetch
        run: neofetch
