name: Integration Test

on:
  workflow_dispatch:

jobs:
  test-macos-arm64:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: System Info
        run: |
          uname -a
          sw_vers

  test-linux-arm64:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: System Info
        run: |
          uname -a
          cat /etc/os-release

  test-linux-amd64:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: System Info
        run: |
          uname -a
          cat /etc/os-release
